# Generated by Django 3.1.7 on 2021-04-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleSingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_field', models.CharField(max_length=120)),
                ('bool_field', models.BooleanField()),
                ('float_field', models.FloatField()),
                ('int_field', models.IntegerField()),
            ],
        ),
    ]
